name: PHP Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: actions/setup-php@v1
      with:
        php-version: 7.4

    - name: Install dependencies
      run: composer install --no-progress --no-suggest

    - name: Run tests
      run: vendor/bin/phpunit tests

    - name: Check code style
      run: vendor/bin/phpcs --standard=PSR12 src tests